[package]
name = "muxfin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Minimal-dependency pure-Rust MP4 muxer for recording applications."
keywords = ["mp4", "video", "muxer", "h264", "multimedia"]
categories = [
  "multimedia",
  "multimedia::encoding",
  "multimedia::video",
  "command-line-utilities",
]
exclude = [
  ".github/",
  ".vscode/",
  "release-notes/",
  "target/",
  "**/*.mp4",
  "**/*.gif",
  "**/*.rgb",
  "**/*.h264",
  "**/*.bak",
]

[dependencies]
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
mkv-element.workspace = true

[dev-dependencies]
lazy_static.workspace = true
proptest.workspace = true
tempfile.workspace = true
criterion.workspace = true
matroska-demuxer.workspace = true
dissonia = "0.1.5"

[[bench]]
name = "muxing"
harness = false
